import Main from "./Main";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="relative min-h-screen bg-gradient-to-br from-rich-black via-oxford-blue/50 to-rich-black overflow-x-hidden">
      <Main />
    </div>
  );
}
